### ISSUE TITLE
Двойной рендер при нажатии на Input при использовании PopoutRoot

### ISSUE THREAD

**Issue by Andrey-Kuzmichev** [ItzNeviKat/router#10]
**Описание**
Если нажать на любой компонент для ввода данных, то происходит двойной рендер. Он введет к тому что клавиатура сразу закрывается после нажатия на компонент input.

**Версия библиотеки**
`0.1.0-beta8`

**Демонстрация**
<image src="https://user-images.githubusercontent.com/40794680/154798828-5bc26a99-a1e4-4f30-930d-a8b3c4938bb7.gif" height="400" />

**Comment by kosheeta** [comment]
Покопавшись в коде VKUI понял, что при открытии попаута он делает `blur` на активном элементе. Сам компонент `PopoutRoot` достаточно костыльный, и учитывая этот баг, который нельзя поправить, я принял решение удалить его из роутера. На данный момент для использования попаутов рекомендую делать такую конструкцию:

```tsx
let { popout = null } = useParams();

return <SplitLayout
  {/* ... */}
  popout={{
    'test-action-sheet': <TestActionSheet />,
    'test-alert': <TestAlert />
  }[popout ?? ''] ?? null}
/>
```
